line-length = 120
indent-width = 4
target-version = "py312"

[lint]
select = ["E4", "E7", "E9", "F", "B", "Q", "I"]
fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
