name: Package and release from manifest.yaml

on:
  push:
    branches:
      - main
jobs:
  package-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: install dify-plugin cli
        run: |
          sudo ./.devcontainer/download_dify_tools.sh
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get pushed commits
        id: get_commits
        run: | 
          git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:"%H" | grep '' > ../commits.txt
      - name: Process commits and create tags
        id: process_commits
        run: |
          while read COMMIT_HASH; do
            echo "Processing commit $COMMIT_HASH"
            git checkout $COMMIT_HASH
            if [ -f manifest.yaml ]; then
              echo "Found manifest.yaml"
              # Extract version from manifest.yaml
              VERSION=$(yq -r '.version' manifest.yaml)
              echo "Version: $VERSION"
              TAG="v$VERSION"
              if git rev-parse $TAG > /dev/null 2>&1; then
                echo "Tag $TAG already exists"
                continue
              fi
              # Create a tag
              git tag $TAG $COMMIT_HASH
              echo "Created tag $TAG"
              # Push the tag
              git push origin $TAG
              echo "Pushed tag $TAG"
            else
              echo "No manifest.yaml found"
            fi
          done < ../commits.txt
            


  